### ISSUE TITLE
pod CrashLoopBackOff,  localEp is different from tdengine-operator-0.tdengine-operator.default.svc.cluster.local:6030 in dnodeEps.json and need reconfigured

### ISSUE THREAD

**Issue by crazyboy988** [taosdata/TDengine-Operator#14]
helm install tdengine-cluster tdengine-0.3.0.tgz -f values.yaml -n tdengine-operator --create-namespace

create with a namespace, but:
NAME                                           READY   STATUS             RESTARTS   AGE
tdengine-cluster-0                             0/1     CrashLoopBackOff   5          4m40s
tdengine-cluster-arbitrator-64779f495b-tnvtd   1/1     Running            0          4m40s

05/19 14:39:57.067581 00000082 UTL ==================================
05/19 14:39:57.067584 00000082 DND dnode storage is initialized at /var/lib/taos/dnode
05/19 14:39:57.067588 00000082 DND step:dnode-storage is initialized
05/19 14:39:57.067612 00000082 DND read file /var/lib/taos/dnode/dnodeCfg.json successed
05/19 14:39:57.067620 00000082 DND dnodeId is set to 1, clusterId is set to a098bf45-0668-4596-94cb-8b1ff72a7936
05/19 14:39:57.069200 00000082 DND successed to write /var/lib/taos/dnode/dnodeCfg.json
05/19 14:39:57.069239 00000082 DND dnode cfg is initialized
05/19 14:39:57.069245 00000082 DND step:dnode-cfg is initialized
05/19 14:39:57.069307 00000082 DND read file /var/lib/taos/dnode/dnodeEps.json successed
05/19 14:39:57.069349 00000082 DND ERROR dnode:1, localEp is different from tdengine-operator-0.tdengine-operator.default.svc.cluster.local:6030 in dnodeEps.json and need reconfigured
05/19 14:39:57.069399 00000082 DND Failed to start TDengine, please check the log at:/var/log/taos

namespace is default for default, is not  tdengine-operator.

**Comment by zitsen** [comment]
seems that the tdengine pod bind to incrrect pvc. Please try to remove the related pvcs, delete the helm release and re-install.
