### ISSUE TITLE
Kubernetes Ingress

### ISSUE THREAD

**Issue by cyronis** [taosdata/TDengine-Operator#17]
Hi,

i installed the Helm Chart on our Kubernetes and the Pods are running, created an NGINX Controller with TCP UDP Proxy but it can only map TCP or UDP on the same Port - when I publish the TCP-6030 Port i get "taos connect failed, reason: Unable to establish connection." if i make a curl command on port 6041 the response is success

is there a chance to access the ClusterIP only over the TCP Port

BR

**Comment by zitsen** [comment]
Sorry for the bad exprience. But the TDengine design requires both the fqdn and port be the same to cluster internal (in k8s, it may be `tdengine-0.tdengine.svc.cluster.local:6030` so I don't think it's easy for developers to handle that much. Only the REST API endpoint (6041) is recommanded as public. If an app want to use native connections, leave it in the same k8s namespace then it do not require ingress.
