### ISSUE TITLE
通过helm安装TDengine之后，监控貌似无法使用，6043端口暴露出来请求无响应

### ISSUE THREAD

**Issue by yuchengao0721** [taosdata/TDengine-Operator#40]
![微信图片_20230510171157](https://github.com/taosdata/TDengine-Operator/assets/30454673/5fe38281-d349-4b1e-852d-f83f1eeb8ec6)
这是我的values.yaml文件，
数据库是正常启动的，我通过GUI能够连接，但是我发现6043端口请求无效，进入pod内执行命令 
taoskeeper
结果为：

> ERRO[0000] create database log error server response: 401 Unauthorized - {"code":855,"desc":"Authentication failure"}  error="server response: 401 Unauthorized - {\"code\":855,\"desc\":\"Authentication failure\"}" model=report module=taosKeeper
panic: server response: 401 Unauthorized - {"code":855,"desc":"Authentication failure"}
goroutine 1 [running]:
github.com/taosdata/taoskeeper/api.(*Reporter).createDatabase(0xc0005d88a0)
        /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/release/build-taoskeeper/api/report.go:72 +0x35a
github.com/taosdata/taoskeeper/api.(*Reporter).Init(0xc000130000, {0x1ddf7a0, 0xc000582ea0})
        /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/release/build-taoskeeper/api/report.go:57 +0x8e
main.main()
        /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/release/build-taoskeeper/main.go:25 +0x6a

想知道如何解决这个问题

**Comment by yuchengao0721** [comment]
root@scarm-tdengine-ych-0:~# taos
Welcome to the TDengine Command Line Interface, Client Version:3.0.2.6
Copyright (c) 2022 by TDengine, all rights reserved.

failed to connect to server, reason: Authentication failure

root@scarm-tdengine-ych-0:~# sudo taos
bash: sudo: command not found
root@scarm-tdengine-ych-0:~# ^C
root@scarm-tdengine-ych-0:~# taoskeeper
ERRO[0000] create database log error server response: 401 Unauthorized - {"code":855,"desc":"Authentication failure"}  error="server response: 401 Unauthorized - {\"code\":855,\"desc\":\"Authentication failure\"}" model=report module=taosKeeper
panic: server response: 401 Unauthorized - {"code":855,"desc":"Authentication failure"}

goroutine 1 [running]:
github.com/taosdata/taoskeeper/api.(*Reporter).createDatabase(0xc00027d500)
        /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/release/build-taoskeeper/api/report.go:72 +0x35a
github.com/taosdata/taoskeeper/api.(*Reporter).Init(0xc0001772c0, {0x1ddf7a0, 0xc0005711e0})
        /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/release/build-taoskeeper/api/report.go:57 +0x8e
main.main()
        /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/release/build-taoskeeper/main.go:25 +0x6a
root@scarm-tdengine-ych-0:~# taosd
05/10 17:50:20.099516 00001268 UTL apoll url not load
05/10 17:50:20.099665 00001268 UTL load from cfg file /etc/taos//taos.cfg success
05/10 17:50:20.099682 00001268 UTL env file:.env not load
05/10 17:50:20.099732 00001268 UTL load from env variables cfg success
05/10 17:50:20.100065 00001268 DND startup path:/root args:taosd
05/10 17:50:20.100589 00001268 UTL apoll url not load
05/10 17:50:20.100702 00001268 UTL load from cfg file /etc/taos//taos.cfg success
05/10 17:50:20.100741 00001268 UTL env file:.env not load
05/10 17:50:20.100794 00001268 UTL load from env variables cfg success
05/10 17:50:20.101991 00001268 UTL                      global config
05/10 17:50:20.102161 00001268 UTL =================================================================
05/10 17:50:20.102174 00001268 UTL env_var      firstEp                  scarm-tdengine-ych-0.scarm-tdengine-ych.aims-scarm.svc.cluster.local:6030
05/10 17:50:20.102182 00001268 UTL default      secondEp                 scarm-tdengine-ych-0.scarm-tdengine-ych.aims-scarm.svc.cluster.local:6030
05/10 17:50:20.102303 00001268 UTL env_var      fqdn                     scarm-tdengine-ych-0.scarm-tdengine-ych.aims-scarm.svc.cluster.local
05/10 17:50:20.102356 00001268 UTL env_var      serverPort               6030
05/10 17:50:20.102386 00001268 UTL default      tempDir                  /tmp/
05/10 17:50:20.102393 00001268 UTL default      minimalTmpDirGB          1.00
05/10 17:50:20.102403 00001268 UTL default      shellActivityTimer       3
05/10 17:50:20.102413 00001268 UTL default      compressMsgSize          -1
05/10 17:50:20.102418 00001268 UTL default      compressColData          -1
05/10 17:50:20.102421 00001268 UTL default      queryPolicy              1
05/10 17:50:20.102424 00001268 UTL default      enableQueryHb            0
05/10 17:50:20.102949 00001268 UTL default      querySmaOptimize         0
05/10 17:50:20.102994 00001268 UTL default      queryPlannerTrace        0
05/10 17:50:20.102999 00001268 UTL default      queryNodeChunkSize       32768
05/10 17:50:20.103002 00001268 UTL default      queryUseNodeAllocator    1
05/10 17:50:20.103004 00001268 UTL default      keepColumnName           0
05/10 17:50:20.103008 00001268 UTL default      smlChildTableName        
05/10 17:50:20.103010 00001268 UTL default      smlTagName               _tag_null
05/10 17:50:20.103014 00001268 UTL default      smlDataFormat            0
05/10 17:50:20.103018 00001268 UTL default      smlBatchSize             10000
05/10 17:50:20.103025 00001268 UTL default      maxMemUsedByInsert       1024
05/10 17:50:20.103055 00001268 UTL default      maxRetryWaitTime         10000
05/10 17:50:20.103062 00001268 UTL default      useAdapter               0
05/10 17:50:20.103066 00001268 UTL default      crashReporting           1
05/10 17:50:20.103122 00001268 UTL default      numOfTaskQueueThreads    4
05/10 17:50:20.103132 00001268 UTL default      dataDir                  /var/lib/taos/
05/10 17:50:20.103159 00001268 UTL default      minimalDataDirGB         2.00
05/10 17:50:20.103197 00001268 UTL default      supportVnodes            16
05/10 17:50:20.103203 00001268 UTL default      maxShellConns            50000
05/10 17:50:20.103206 00001268 UTL default      statusInterval           1
05/10 17:50:20.103210 00001268 UTL default      minSlidingTime           10
05/10 17:50:20.103450 00001268 UTL default      minIntervalTime          1
05/10 17:50:20.104791 00001268 UTL default      maxNumOfDistinctRes      10000000
05/10 17:50:20.104910 00001268 UTL default      countAlwaysReturnValue   1
05/10 17:50:20.104998 00001268 UTL default      queryBufferSize          -1
05/10 17:50:20.106227 00001268 UTL default      printAuth                0
05/10 17:50:20.106990 00001268 UTL default      queryRspPolicy           0
05/10 17:50:20.107233 00001268 UTL default      numOfRpcThreads          4
05/10 17:50:20.107814 00001268 UTL default      numOfRpcSessions         2000
05/10 17:50:20.107883 00001268 UTL default      numOfCommitThreads       4
05/10 17:50:20.107888 00001268 UTL default      numOfMnodeReadThreads    1
05/10 17:50:20.107891 00001268 UTL default      numOfVnodeQueryThreads   16
05/10 17:50:20.107894 00001268 UTL default      ratioOfVnodeStreamThrea  1.00
05/10 17:50:20.107902 00001268 UTL default      numOfVnodeFetchThreads   4
05/10 17:50:20.107952 00001268 UTL default      numOfVnodeRsmaThreads    8
05/10 17:50:20.107957 00001268 UTL default      numOfQnodeQueryThreads   16
05/10 17:50:20.107961 00001268 UTL default      numOfSnodeSharedThreads  2
05/10 17:50:20.107964 00001268 UTL default      numOfSnodeUniqueThreads  2
05/10 17:50:20.107973 00001268 UTL default      rpcQueueMemoryAllowed    622328627
05/10 17:50:20.107987 00001268 UTL default      syncElectInterval        25000
05/10 17:50:20.107993 00001268 UTL default      syncHeartbeatInterval    1000
05/10 17:50:20.107995 00001268 UTL default      syncHeartbeatTimeout     20000
05/10 17:50:20.107998 00001268 UTL default      vndCommitMaxInterval     60000
05/10 17:50:20.108001 00001268 UTL env_var      monitor                  1
05/10 17:50:20.108003 00001268 UTL env_var      monitorInterval          30
05/10 17:50:20.108006 00001268 UTL default      monitorFqdn              
05/10 17:50:20.108008 00001268 UTL default      monitorPort              6043
05/10 17:50:20.108011 00001268 UTL default      monitorMaxLogs           100
05/10 17:50:20.108014 00001268 UTL default      monitorComp              0
05/10 17:50:20.108019 00001268 UTL default      crashReporting           1
05/10 17:50:20.108023 00001268 UTL default      telemetryReporting       1
05/10 17:50:20.108026 00001268 UTL default      telemetryInterval        43200
05/10 17:50:20.108030 00001268 UTL default      telemetryServer          telemetry.taosdata.com
05/10 17:50:20.108033 00001268 UTL default      telemetryPort            80
05/10 17:50:20.108036 00001268 UTL default      transPullupInterval      2
05/10 17:50:20.108040 00001268 UTL default      mqRebalanceInterval      2
05/10 17:50:20.108066 00001268 UTL default      ttlUnit                  86400
05/10 17:50:20.108072 00001268 UTL default      ttlPushInterval          86400
05/10 17:50:20.108075 00001268 UTL default      uptimeInterval           300
05/10 17:50:20.108078 00001268 UTL default      queryRsmaTolerance       1000
05/10 17:50:20.108088 00001268 UTL default      walFsyncDataSizeLimit    104857600
05/10 17:50:20.108094 00001268 UTL default      udf                      1
05/10 17:50:20.108098 00001268 UTL default      udfdResFuncs             
05/10 17:50:20.108100 00001268 UTL default      udfdLdLibPath            
05/10 17:50:20.108104 00001268 UTL default      disableStream            0
05/10 17:50:20.108106 00001268 UTL default      configDir                /etc/taos/
05/10 17:50:20.108109 00001268 UTL default      scriptDir                /etc/taos/
05/10 17:50:20.108116 00001268 UTL default      logDir                   /var/log/taos/
05/10 17:50:20.108125 00001268 UTL default      minimalLogDirGB          1.00
05/10 17:50:20.108131 00001268 UTL default      numOfLogLines            10000000
05/10 17:50:20.108245 00001268 UTL default      asyncLog                 1
05/10 17:50:20.108660 00001268 UTL default      logKeepDays              0
05/10 17:50:20.108673 00001268 UTL default      debugFlag                0
05/10 17:50:20.108677 00001268 UTL default      simDebugFlag             143
05/10 17:50:20.108680 00001268 UTL default      tmrDebugFlag             131
05/10 17:50:20.108683 00001268 UTL default      uDebugFlag               131
05/10 17:50:20.108686 00001268 UTL default      rpcDebugFlag             131
05/10 17:50:20.108689 00001268 UTL default      jniDebugFlag             131
05/10 17:50:20.108692 00001268 UTL default      qDebugFlag               131
05/10 17:50:20.108694 00001268 UTL default      cDebugFlag               131
05/10 17:50:20.108697 00001268 UTL default      dDebugFlag               131
05/10 17:50:20.108700 00001268 UTL default      vDebugFlag               131
05/10 17:50:20.108702 00001268 UTL default      mDebugFlag               131
05/10 17:50:20.108705 00001268 UTL default      wDebugFlag               131
05/10 17:50:20.108708 00001268 UTL default      sDebugFlag               131
05/10 17:50:20.108711 00001268 UTL default      tsdbDebugFlag            131
05/10 17:50:20.108713 00001268 UTL default      tqDebugFlag              131
05/10 17:50:20.109007 00001268 UTL default      fsDebugFlag              131
05/10 17:50:20.109020 00001268 UTL default      udfDebugFlag             131
05/10 17:50:20.109023 00001268 UTL default      smaDebugFlag             131
05/10 17:50:20.109025 00001268 UTL default      idxDebugFlag             131
05/10 17:50:20.109028 00001268 UTL default      tdbDebugFlag             131
05/10 17:50:20.109031 00001268 UTL default      metaDebugFlag            131
05/10 17:50:20.109033 00001268 UTL default      timezone                 Asia/Shanghai (CST, +0800)
05/10 17:50:20.109037 00001268 UTL default      locale                   en_US.UTF-8
05/10 17:50:20.109040 00001268 UTL default      charset                  UTF-8
05/10 17:50:20.109042 00001268 UTL default      assert                   1
05/10 17:50:20.109045 00001268 UTL default      enableCoreFile           1
05/10 17:50:20.109123 00001268 UTL default      numOfCores               8.00
05/10 17:50:20.109132 00001268 UTL default      SSE42                    0
05/10 17:50:20.109135 00001268 UTL default      AVX                      0
05/10 17:50:20.109139 00001268 UTL default      AVX2                     0
05/10 17:50:20.109142 00001268 UTL default      FMA                      0
05/10 17:50:20.109147 00001268 UTL default      SIMD-builtins            0
05/10 17:50:20.109156 00001268 UTL default      tagFilterCache           0
05/10 17:50:20.109185 00001268 UTL default      openMax                  1048576
05/10 17:50:20.109194 00001268 UTL default      streamMax                16
05/10 17:50:20.109198 00001268 UTL default      pageSizeKB               4
05/10 17:50:20.109200 00001268 UTL default      totalMemoryKB            6077428
05/10 17:50:20.109203 00001268 UTL default      os sysname               Linux
05/10 17:50:20.109206 00001268 UTL default      os nodename              scarm-tdengine-ych-0
05/10 17:50:20.109209 00001268 UTL default      os release               5.4.238-1.el7.elrepo.x86_64
05/10 17:50:20.109216 00001268 UTL default      os version               #1 SMP Tue Mar 21 11:19:15 EDT 2023
05/10 17:50:20.109222 00001268 UTL default      os machine               x86_64
05/10 17:50:20.109225 00001268 UTL default      version                  3.0.2.6
05/10 17:50:20.109228 00001268 UTL default      compatible_version       3.0.0.0
05/10 17:50:20.109260 00001268 UTL default      gitinfo                  0993813213efe3e18a0fcb5ab26538b811451798
05/10 17:50:20.109267 00001268 UTL default      buildinfo                Built at 2023-02-23 14:51
05/10 17:50:20.109270 00001268 UTL =================================================================
05/10 17:50:20.113972 00001268 DND start to init dnode env
05/10 17:50:20.114249 00001268 DND succceed to read mnode file /var/lib/taos//dnode/dnode.json
05/10 17:50:20.114362 00001268 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
05/10 17:50:20.114381 00001268 DND file:/var/lib/taos//qnode/qnode.json not exist
05/10 17:50:20.114393 00001268 DND file:/var/lib/taos//snode/snode.json not exist
05/10 17:50:21.114749 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:1
05/10 17:50:22.114988 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:2
05/10 17:50:23.115186 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:3
05/10 17:50:24.115406 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:4
05/10 17:50:25.115608 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:5
05/10 17:50:26.115794 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:6
05/10 17:50:27.116023 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:7
05/10 17:50:28.116193 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:8
05/10 17:50:29.116393 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:9
05/10 17:50:30.116588 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:10
05/10 17:50:31.116813 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:11
05/10 17:50:32.117019 00001268 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:12
05/10 17:50:32.117090 00001268 DND ERROR failed to create dnode since Resource temporarily unavailable
05/10 17:50:32.117150 00001268 DND ERROR failed to init dnode since Resource temporarily unavailable

这是我在pod内执行命令的响应结果

**Comment by yuchengao0721** [comment]
我进入数据库安装目录看了一下，你们提供的helm压缩包貌似有很多配置不被支持，比如开启监控必须的几个配置，都没有在value.yaml文件中体现出来，我感觉还不如直接把安装目录下面的 etc/taos 目录挂载出来，更方便集群部署的时候进行修改
下面这个是我修改后的helm压缩包，希望你们在下个版本能够完善一下呢。

**Comment by sangshuduo** [comment]
> 我进入数据库安装目录看了一下，你们提供的helm压缩包貌似有很多配置不被支持，比如开启监控必须的几个配置，都没有在value.yaml文件中体现出来，我感觉还不如直接把安装目录下面的 etc/taos 目录挂载出来，更方便集群部署的时候进行修改 下面这个是我修改后的helm压缩包，希望你们在下个版本能够完善一下呢。

欢迎 PR 的方式
