### ISSUE TITLE
Need to build new image to support tdengine 2.3 +

### ISSUE THREAD

**Issue by codering** [taosdata/TDengine-Operator#9]

**Comment by sangshuduo** [comment]
will do.

**Comment by codering** [comment]
should be 2.4 now

**Comment by zitsen** [comment]
2.4 introduce a new web interface of TDengine, which is a independent tool out of taosd. We'll use another way to support different use cases. Maybe it'll take 2~3 days in this week.

**Comment by codering** [comment]
Any update ?

**Comment by zitsen** [comment]
Published TDengine 2.3.5.0 and 2.4.0.0 .
